---
abstract: 'reformat your text within Padre'
author:
  - 'Jerome Quelin <jquelin@gmail.com>'
build_requires:
  Padre: 0.43
  Test::More: 0
  Text::Autoformat: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Padre-Plugin-Autoformat
provides:
  Padre::Plugin::Autoformat:
    file: lib/Padre/Plugin/Autoformat.pm
    version: v1.2.0
requires:
  File::Basename: 0
  File::Spec::Functions: 0
  Module::Util: 0
resources:
  homepage: http://padre.perlide.org/
  license: http://dev.perl.org/licenses/
  repository: http://svn.perlide.org/padre/trunk/Padre-Plugin-Autoformat/
version: v1.2.0
